project:
  type: website
  output-dir: ../qbits-notes

website:
  title: "QFey"
  site-url: https://qfey.in/qbits
  navbar:
    right:
      - text: Home
        href: ../index.html
      - text: About
        href: https://qubitai.in/about.html
        target: _blank
      - text: Blogs
        href: https://qfey.in/qscribe-blog/  
      - icon: github
        href: https://github.com/rvbug
        target: _blank
      - icon: globe
        href: https://qubitai.in/
        target: _blank
      - text: QFey
        href: https://qfey.in/
        target: _blank
  sidebar: 
    contents:
      - section: "Reinforcement Learning"
        contents: "RL/*.qmd"
      - section: "Quantum ML"
        contents: "QML/*.qmd"

format:
  html:
    theme: darkly
    toc: true
    toc-location: right
    toc-depth: 3
    anchor-sections: true
    smooth-scroll: true
    code-copy: true
    code-fold: false
