project:
  type: manuscript

manuscript:
  article: manuscript.qmd

format:
  html:
    toc: true
    code-fold: false
  pdf:
    documentclass: article
    include-in-header:
      - text: |
          \usepackage{amsmath,amsfonts,amssymb}
          \usepackage{graphicx}
          \usepackage{hyperref}